name: "Test service"
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '.run/**'
      - 'api/**'
      - 'features/**'
      - 'config/**'
      - 'deployments/**'
      - '*.md'
    tags:
      - v*

  pull_request:
    types: [ opened, synchronize ]
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '.run/**'
      - 'api/**'
      - 'features/**'
      - 'config/**'
      - 'deployments/**'
      - '*.md'

  workflow_dispatch:

jobs:

  # Generate mocks
  generate-mocks:
    name: "Generate mocks"
    runs-on: ubuntu-latest
    container: vektra/mockery:v2.38.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate mocks
        run: |
          mockery --all

      - name: Commit mocks
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Gen] Generated mocks"

  # Run unit tests
  tests:
    name: "Run unit tests"
    needs:
      - generate-mocks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1

      - name: Install dependencies and run tests
        run: |
          go mod download
          go test -v ./...